vich_uploader:
    db_driver: orm

    mappings:
        car:
            uri_prefix: /images/car
            upload_destination: '%kernel.project_dir%/public/images/car'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
